services:
  pwa-node:
    build:
      context: pwa/
      target: base-node-dev
    tty: true # https://github.com/facebook/create-react-app/issues/8688
    ports:
      # HTTP
      - '80:3000'
    volumes:
      - ./pwa:/var/www:cached
      - ./pwa/node_modules:/var/www/node_modules:delegated
      - ./pwa/src:/var/www/src:cached
    environment:
      USER_ID: ${USER_ID:-0}
      GROUP_ID: ${GROUP_ID:-0}

      # General settings
      # dev, staging, prod
      ENVIRONMENT: dev
