version: '3.4'

services:
  db:
    image: postgres:latest
    healthcheck:
      test: [ 'CMD', 'pg_isready', '--username=dbUser', '--dbname=dbApp' ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-prod:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: dbPassword
      POSTGRES_DB: dbApp

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: dbAdminPassword
    volumes:
      - ./.docker/pgadmin/servers.json:/pgadmin4/servers.json:ro

  redis:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass redisPassword
    volumes:
      - redis-prod:/data

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: redisApp
      REDIS_1_AUTH: redisPassword
    depends_on:
      - redis
    ports:
      - 82:80

  php:
    build:
      context: .
      target: app-php
    healthcheck:
      start_period: 1m40s
    depends_on:
      - db
      - redis
    volumes:
      - craft-cpresources-prod:/app/web/cpresources
    environment:
      USER_ID: ${USER_ID:-0}
      GROUP_ID: ${GROUP_ID:-0}

      # PHP Settings
      PHP_MAX_EXECUTION_TIME: 0

      # Craft general settings
      ENVIRONMENT: prod # dev, staging, prod
      APP_ID: CraftCMS--224c362b-5476-42f8-8c5b-1742fa24e4d5
      SECURITY_KEY: oA6-oxNqj2xtG1lTw9b6T6NOE9_SaEFz

      # Craft database settings
      DB_DRIVER: pgsql
      DB_SERVER: db
      #DB_PORT: 5432
      DB_USER: dbUser
      DB_PASSWORD: dbPassword
      DB_DATABASE: dbApp
      #DB_SCHEMA: public
      #DB_TABLE_PREFIX:

      # URL & path settings
      ASSETS_URL: http://localhost/assets
      SITE_URL: http://localhost

      # Craft & Plugin Licenses (When the actual license has a $, please replace them all with $$)
      LICENSE_KEY: $LICENSE_KEY
      PLUGIN_BLITZ_LICENSE: $PLUGIN_BLITZ_LICENSE
      PLUGIN_COMMERCE_LICENSE: $PLUGIN_COMMERCE_LICENSE
      PLUGIN_FREEFORM_LICENSE: $PLUGIN_FREEFORM_LICENSE
      PLUGIN_NAVIGATION_LICENSE: $PLUGIN_NAVIGATION_LICENSE
      PLUGIN_RETOUR_LICENSE: $PLUGIN_RETOUR_LICENSE
      PLUGIN_SEOMATIC_LICENSE: $PLUGIN_SEOMATIC_LICENSE
      PLUGIN_TRANSLATIONS_ADMIN_LICENSE: $PLUGIN_TRANSLATIONS_ADMIN_LICENSE

      # Redis settings
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redisPassword
      REDIS_DEFAULT_DB: 0
      REDIS_CRAFT_DB: 3

      # Google Analytics settings
      # GA_TRACKING_ID:

  nginx:
    build:
      context: .
      target: app-nginx
    healthcheck:
      test: test -e /var/run/nginx.pid || exit 1
    depends_on:
      - php
    ports:
      - 80:80
      # - 443:443
    volumes:
      - craft-cpresources-prod:/app/web/cpresources
    environment:
      USER_ID: ${USER_ID:-0}
      GROUP_ID: ${GROUP_ID:-0}
      #USE_HTTPS: 'true'

volumes:
  postgres-prod:
  redis-prod:
  craft-cpresources-prod:
