services:
  redis:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass redisPassword
    volumes:
      - redis-prod:/data

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: redisApp
      REDIS_1_AUTH: redisPassword
    depends_on:
      - redis
    ports:
      # HTTP
      - '82:80'

  cms-php:
    build:
      context: cms/
      target: app-php
    healthcheck:
      start_period: 1m40s
    depends_on:
      - db
      - redis
    volumes:
      - craft-cpresources-prod:/var/www/web/cpresources:delegated
    environment:
      USER_ID: ${USER_ID:-0}
      GROUP_ID: ${GROUP_ID:-0}

      # PHP Settings
      PHP_MAX_EXECUTION_TIME: 0

      # Craft general settings
      ENVIRONMENT: prod # dev, staging, prod
      APP_ID: CraftCMS--224c362b-5476-42f8-8c5b-1742fa24e4d5
      SECURITY_KEY: oA6-oxNqj2xtG1lTw9b6T6NOE9_SaEFz

      # Craft database settings
      DB_DRIVER: pgsql
      DB_SERVER: db
      DB_PORT: 5432
      DB_USER: dbUser
      DB_PASSWORD: dbPassword
      DB_DATABASE: dbApp
      DB_SCHEMA: public
      DB_TABLE_PREFIX:

      # URL & path settings
      ASSETS_URL: http://localhost/assets
      SITE_URL: http://localhost

      # Craft & Plugin Licenses (When the actual license has a $, please replace them all with $$)
      LICENSE_KEY: $LICENSE_KEY
      PLUGIN_BLITZ_LICENSE: $PLUGIN_BLITZ_LICENSE
      PLUGIN_COMMERCE_LICENSE: $PLUGIN_COMMERCE_LICENSE
      PLUGIN_FREEFORM_LICENSE: $PLUGIN_FREEFORM_LICENSE
      PLUGIN_NAVIGATION_LICENSE: $PLUGIN_NAVIGATION_LICENSE
      PLUGIN_RETOUR_LICENSE: $PLUGIN_RETOUR_LICENSE
      PLUGIN_SEOMATIC_LICENSE: $PLUGIN_SEOMATIC_LICENSE
      PLUGIN_TRANSLATIONS_ADMIN_LICENSE: $PLUGIN_TRANSLATIONS_ADMIN_LICENSE

      # Redis settings
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redisPassword
      REDIS_DEFAULT_DB: 0
      REDIS_CRAFT_DB: 3

      # Google Analytics settings
      # GA_TRACKING_ID:

  cms-nginx:
    build:
      context: cms/
      target: app-nginx
    healthcheck:
      test: test -e /var/run/nginx.pid || exit 1
    depends_on:
      - cms-php
    ports:
      # HTTP
      - '80:80'
      # HTTPS
      #- '443:443'
      # HTTP/3
      #- '443:443/udp'
    volumes:
      - craft-cpresources-prod:/var/www/web/cpresources:ro,delegated
    environment:
      USER_ID: ${USER_ID:-0}
      GROUP_ID: ${GROUP_ID:-0}
      #USE_HTTPS: 'true'

volumes:
  redis-prod:
  craft-cpresources-prod:
