services:
  db:
    image: mariadb:latest
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '--user=dbUser', '--password=dbPassword' ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dbAdminPassword
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: dbPassword
      MYSQL_DATABASE: dbApp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      # HTTP
      - '81:80'
    environment:
      UPLOAD_LIMIT: 100M
      PMA_HOST: db

volumes:
  db-mysql:
